animals = ['bear', 'python', 'peacock', 'kangaroo', 'whale', 'platypus']
print "1. The animal at 1 is the second animal and is a %s." %animals[1]
print "2. The third amimal is at 2 and is a %s." % animals[2]
print "3. The first amimal is at 0 and is a %s." % animals[0]
print "4. The animal at 3 is the fourth animal and is a %s." % animals[3]
print "5. The fifth animal is at 4 and is a %s." % animals[4]
print "6. The animal at 2 is the third animal and is a %s." % animals[2]
print "7. The sixth animal is at 5 and is a %s." % animals[5]
print "8. The animal at 4 is the fifth animal and is a %s." % animals[4]
